### ISSUE TITLE
Unhandled rejection Error: Cannot find module

### ISSUE THREAD

**Issue by ksamc** [netlify/netlify-lambda#111]
I am getting the following error when trying to run ```netlify-lambda serve```:

Any ideas on how to get around this issue? Any help would be appreciated.

```
> test@1.0.0 start:lambda /tmp/test
> netlify-lambda serve src/lambda

netlify-lambda: Starting server
Lambda server is listening on 9000
Unhandled rejection Error: Cannot find module '/tmp/test/lambda/hello'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.clearCache (/tmp/test/node_modules/netlify-lambda/lib/serve.js:130:36)
    at /tmp/test/node_modules/netlify-lambda/bin/cmd.js:38:16
    at Array.forEach (<anonymous>)
    at Watching.handler (/tmp/test/node_modules/netlify-lambda/bin/cmd.js:37:32)
    at compiler.hooks.done.callAsync (/tmp/test/node_modules/webpack/lib/Watching.js:98:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/test/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/tmp/test/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/tmp/test/node_modules/webpack/lib/Watching.js:97:28)
    at onCompiled (/tmp/test/node_modules/webpack/lib/Watching.js:47:18)
    at hooks.afterCompile.callAsync.err (/tmp/test/node_modules/webpack/lib/Compiler.js:630:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/test/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/tmp/test/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/tmp/test/node_modules/webpack/lib/Compiler.js:627:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/test/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
```

```
# package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start:lambda": "netlify-lambda serve src/lambda"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "netlify-lambda": "^1.3.1"
  }
}
```

```
# netlify.toml
[build]
  Functions = "lambda"
```

**Comment by ksamc** [comment]
Thanks @sw-yx. Will give that a try.
