### ISSUE TITLE
introsepctSchema with apollo-server-lambda and netlify lambda failing

### ISSUE THREAD

**Issue by kedarguy** [netlify/netlify-lambda#117]
I am trying to get an apollo-server with schema stitching to work with netlify functions.

when trying to run introspectSchema, I get a bug from which my best guess has to do with the babel configuration coming from netlify-lambda.

I catch the following error in the try catch before `mergeSchemas`
`TypeError: s is not a function` I narrowed it down to being the `introspectSchema` function that is throwing the error

while debugging I tried running pretty much the same code with `apollo-server` instead of `apollo-server-lambda` and it works

here is the lambda version that catches the error when running with `netlify-lambda serve src/functions`, the playground actually does start but without the remote schema.

```
const {
  ApolloServer,
  gql,
  introspectSchema,
  makeExecutableSchema,
  makeRemoteExecutableSchema,
  mergeSchemas
} = require("apollo-server-lambda");
const { createHttpLink } = require("apollo-link-http");
const fetch = require("node-fetch");

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => "Hello world 8!"
  }
};

const localSchema = makeExecutableSchema({
  typeDefs,
  resolvers
});

const createCmsSchema = async () => {
  const cmsSchemaLink = createHttpLink({
    uri: `https://www.someurl.com`,
    fetch
  });

  const schema = await introspectSchema(cmsSchemaLink);

  return makeRemoteExecutableSchema({
    schema,
    link: cmsSchemaLink
  });
};

const runHandler = (event, context, handler) =>
  new Promise((resolve, reject) => {
    const callback = (error, body) => (error ? reject(error) : resolve(body));

    handler(event, context, callback);
  });

const run = async (event, context) => {
  // Create your connections here
  const schemaArr = [localSchema];

  try {
    const cmsSchema = await createCmsSchema();
    schemaArr.push(cmsSchema);
    console.log("sucess with cms");
  } catch (err) {
    console.log("failed with cms schema", err);
  }
  const schemas = mergeSchemas({
    schemas: schemaArr
  });
  const server = new ApolloServer({
    schema: schemas,
    introspection: true,
    playground: true
  });
  const handler = server.createHandler({
    cors: {
      origin: "*",
      credentials: true,
      allowedHeaders: ["ContentType", "content-type", "Origin", "Accept"]
    }
  });
  const response = await runHandler(event, context, handler);

  return response;
};

exports.handler = run;
```

and the similar code that works when running a local node server: 

```
// const {
//   ApolloServer,
//   gql,
//   introspectSchema,
//   makeExecutableSchema,
//   makeRemoteExecutableSchema,
//   mergeSchemas
// } = require("apollo-server-lambda");
const {
  ApolloServer,
  gql,
  introspectSchema,
  makeExecutableSchema,
  makeRemoteExecutableSchema,
  mergeSchemas
} = require("apollo-server");
const { createHttpLink } = require("apollo-link-http");
const fetch = require("node-fetch");

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => "Hello world 8!"
  }
};

const localSchema = makeExecutableSchema({
  typeDefs,
  resolvers
});

const createCmsSchema = async () => {
  const cmsSchemaLink = createHttpLink({
    uri: `https://www.someurl.com`,
    fetch
  });

  const schema = await introspectSchema(cmsSchemaLink);

  return makeRemoteExecutableSchema({
    schema,
    link: cmsSchemaLink
  });
};

const runHandler = (event, context, handler) =>
  new Promise((resolve, reject) => {
    const callback = (error, body) => (error ? reject(error) : resolve(body));

    handler(event, context, callback);
  });

const run = async (event, context) => {
  // Create your connections here
  const schemaArr = [localSchema];

  try {
    const cmsSchema = await createCmsSchema();
    schemaArr.push(cmsSchema);
    console.log("sucess with cms");
  } catch (err) {
    console.log("failed with cms schema", err);
  }
  const schemas = mergeSchemas({
    schemas: schemaArr
  });
  const server = new ApolloServer({
    schema: schemas,
    introspection: true,
    playground: true
  });
  const handler = server.createHandler({
    cors: {
      origin: "*",
      credentials: true,
      allowedHeaders: ["ContentType", "content-type", "Origin", "Accept"]
    }
  });
  const response = await runHandler(event, context, handler);

  // Destroy your connections here

//   return response;
    server.listen().then(({ url }) => {
      console.log(`🚀  Server ready at ${url}`);
    });
};

// exports.handler = run;

try {
  run();
} catch (e) {
  console.log("error:", e);
}
```

will appreciate any help figuring this out.

**Comment by sw-yx** [comment]
hey kedarguy,

got a minimal repo i can clone? if not its ok i can try to replicate your situation but figured i would ask in case its easy for you to put up a repo.

i'm keen on helping you figure this out

**Comment by kedarguy** [comment]
Hey, I will set up a repo later today and post it here.

Thanks!

**Comment by kedarguy** [comment]
hey here is the [repo]( https://github.com/kedarguy/netlify-apollo-introspection-bug)

instructions in the readme

**Comment by sw-yx** [comment]
hi @kedarguy 

so i havent solved it but at least was able to reproduce it. first thing to observe is that you're using an old `netlify-lambda` version there. so i upgraded to v1.x and `babel-loader` as well. then i [turned off minification](https://github.com/netlify/netlify-lambda#webpack-configuration) so we can see the error. now i can see that "s is not a function" is actually "fetcher is not a function":

```
Request from ::1: GET /graphql
failed with remote schema TypeError: fetcher is not a function
    at /Users/swyx/Work/testbeds/netlify-apollo-introspection-bug/dist/server/graphql.js:65619:13
    at new Subscription (/Users/swyx/Work/testbeds/netlify-apollo-introspection-bug/dist/server/graphql.js:40837:34)
    at Observable.subscribe (/Users/swyx/Work/testbeds/netlify-apollo-introspection-bug/dist/server/graphql.js:40916:14)
    at /Users/swyx/Work/testbeds/netlify-apollo-introspection-bug/dist/server/graphql.js:14723:20
    at new Promise (<anonymous>)
    at Module.toPromise (/Users/swyx/Work/testbeds/netlify-apollo-introspection-bug/dist/server/graphql.js:14722:12)


# etc
```

i made a pr to do that for you too https://github.com/kedarguy/netlify-apollo-introspection-bug/pull/1

upon further investigation, `fetcher` seems to be what you are supplying with `node-fetch`, which when we build has this stupid warning

```
WARNING in /Users/swyx/Work/testbeds/netlify-apollo-introspection-bug/node_modules/encoding/lib/iconv-loader.js 9:12-34
Critical dependency: the request of a dependency is an expression
 @ /Users/swyx/Work/testbeds/netlify-apollo-introspection-bug/node_modules/encoding/lib/encoding.js
 @ /Users/swyx/Work/testbeds/netlify-apollo-introspection-bug/node_modules/apollo-server-env/node_modules/node-fetch/lib/index.es.js

# etc
```


this is a highly unhelpful warning but i managed to narrow it down to here

![image](https://user-images.githubusercontent.com/6764957/52622910-128c7600-2e4f-11e9-8b04-41aa991df7c8.png)

this means to me that node-fetch is being imported as ESModules (or some thing like that.. i am really hazy with terminology here). so when i coerce to use fetcher.default... (disabling the webpack build in the `serve` command by going into `node_modules/.bin/netlify-lambda`...)

![image](https://user-images.githubusercontent.com/6764957/52623040-64350080-2e4f-11e9-9b1b-748038abdd97.png)

i get a working run!!

![image](https://user-images.githubusercontent.com/6764957/52623079-77e06700-2e4f-11e9-8cf0-54527b18d294.png)




so we know the proximate symptom of this issue, which is that node-fetch is being imported wrongly or in an incompatible way. so if i change ONE LINE in your code...

```js
const remoteSchemaLink = createHttpLink({
    uri: `https://api-uswest.graphcms.com/v1/cjs0xy18i740h01f96jatko7r/master`,
    fetch: fetch.default // instead of `fetch: fetch`
  });
```

it now works.

LOL!

**Comment by sw-yx** [comment]
related issues

https://github.com/bitinn/node-fetch/issues/450

https://github.com/webpack/webpack/issues/4742

urgh.

**Comment by kedarguy** [comment]
Awsome, thanks a lot @sw-yx, really enjoying Netlify!
