### ISSUE TITLE
Lambda Server Crashes on Function Change

### ISSUE THREAD

**Issue by AryanJ-NYC** [netlify/netlify-lambda#146]
First of all, thanks for the awesome tool! This makes debugging a ton easier.

I am running `netlify-lambda` v1.4.5 and start the server with `npx netlify-lambda serve ./functions`.

I've started with a simple function in `./functions/submitEmailAddress.js`: 

```
exports.handler = function(event, context, callback) {
  console.log({ event });
  callback(null, {
    statusCode: 200,
  });
};
```

Whenever I make _any_ change to that function and save, the lambda server comes crashing down:

```
Hash: 34fff62469f17c38261f
Version: webpack 4.28.4
Time: 369ms
Built at: 04/24/2019 9:58:27 AM
                Asset      Size  Chunks             Chunk Names
submitEmailAddress.js  1.04 KiB       0  [emitted]  submitEmailAddress
Entrypoint submitEmailAddress = submitEmailAddress.js
[0] ./submitEmailAddress.js 135 bytes {0} [built]
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9000
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Function.listen (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/express/lib/application.js:618:24)
    at Object.exports.listen (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/netlify-lambda/lib/serve.js:179:7)
    at Watching.handler (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/netlify-lambda/bin/cmd.js:38:26)
    at compiler.hooks.done.callAsync (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/webpack/lib/Watching.js:98:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Watching._done (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/webpack/lib/Watching.js:97:28)
    at compiler.emitRecords.err (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/webpack/lib/Watching.js:72:19)
    at Compiler.emitRecords (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/webpack/lib/Compiler.js:375:39)
    at compiler.emitAssets.err (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/webpack/lib/Watching.js:53:20)
    at hooks.afterEmit.callAsync.err (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/webpack/lib/Compiler.js:361:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at asyncLib.forEach.err (/Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/webpack/lib/Compiler.js:358:27)
    at /Users/aryanjabbari/Documents/projects/reactandtypescript.dev/node_modules/neo-async/async.js:2825:7
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

I run a Gatsby server which does _not_ recompile when I change this function.

My `netlify.toml` is as follows:

```
[build]
  functions = "./.netlify/functions"
```

## Update
Now using [Netlify Dev](https://www.netlify.com/products/dev/) (😍) and my function is hot reloading there just fine. No longer blocked but this issue with `netlify-lambda` still remains (for me, at least).

**Comment by sw-yx** [comment]
EADDRINUSE :::9000 seems weird. what else is on that port? `lsof -i -n -P | grep TCP | grep :900`

**Comment by AryanJ-NYC** [comment]
The lambda server is (well, _was_) on port 9000.

**Comment by sw-yx** [comment]
i cant replicate this. do you still want to pursue this or happy to close in favor of netlify dev?

**Comment by AryanJ-NYC** [comment]
I'm personally OK closing in favor of Netlify Dev. However, would like to leave some steps to reproduce in case this needs to be reopened in the future:

1. Clone https://github.com/AryanJ-NYC/reactandtypescript.dev
2. Run `npx netlify-lambda serve ./functions`
3. Edit and save `/functions/submitEmailAddress.js`
4. Watch it crash

**Comment by sw-yx** [comment]
good stuff

**Comment by BrandonNoad** [comment]
I am experiencing the exact same behaviour. 

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9000
```

**Comment by jessepinho** [comment]
Can confirm that I am also experiencing this behavior

**Comment by madebycaliper** [comment]
I'm also experiencing this and would like to continue using this package and not Netlify Dev, as I've never used it and already have this setup. Thanks!

**Comment by sw-yx** [comment]
ok this is a pattern. i think this was introduced with @codepunkt's PR here https://github.com/netlify/netlify-lambda/pull/141

if anyone is free to take a look to fix i'd be much obliged, if not please downgrade to v1.4.4 or below for the time being

**Comment by sw-yx** [comment]
actually please try v1.4.7. i tried to fix it here https://github.com/netlify/netlify-lambda/compare/v1.4.5...v1.4.6

PR's welcome in future folks :) i dont use this actively and am just volunteering my time

**Comment by madebycaliper** [comment]
thanks @sw-yx ! I can confirm that upgrading to 1.4.7 solved this issue for me. I wish I could help more but I'm new to all this stuff. Maybe some day...

**Comment by sw-yx** [comment]
haha np. we’re all stretched thin.
