### ISSUE TITLE
Netlify Dev error "Function invocation failed" and can't access to routes

### ISSUE THREAD

**Issue by dalisoft** [netlify/netlify-lambda#158]
Hello and thanks for great support/app/platform.

[This](https://github.com/dalisoft/fastify-dev-env) is example.

In localhost, when trying to run, error was happening.
```bash
Lambda server is listening on 9000
Request from ::ffff:127.0.0.1: GET /server
-c webpack.functions.js serve functions
Error occured with module ConsoleMD
!#green([*Server*]: started in *DEVELOPMENT* mode)
Response with status 500 in 349 ms.
Error during invocation:  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.dirname (path.js:1121:5)
    at resolve (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:31837:22)
    at ../node_modules/app-root-path/lib/app-root-path.js.module.exports (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:31720:20)
    at Object.<anonymous> (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:31683:18)
    at Object.../node_modules/app-root-path/index.js (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:31684:30)
    at __webpack_require__ (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:20:30)
    at Object.../node_modules/fastify-oas/lib/openapi/constructor.js (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:64427:14)
    at __webpack_require__ (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:20:30)
    at Object.../node_modules/fastify-oas/lib/openapi/index.js (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:64656:21)
```

**Comment by sw-yx** [comment]
i dont know whether this error is coming from netlify-lambda or aws-serverless-express. can you investigate? also you could try using `netlify dev`, so that you dont need to run it through webpack.

**Comment by dalisoft** [comment]
For me `netlify dev` isn't available, only `netlify-lambda serve` available.
It is ok? or i am missing something?

**Comment by dalisoft** [comment]
Without my own webpack config, same thing.
```bash
dalisoft-MBP:fastify-dev-env dalisoft$ npx netlify-lambda serve functions
netlify-lambda: Starting server
Hash: 75b8d114cacd5fe0f9c9
Version: webpack 4.32.0
Time: 38621ms
Built at: 20.05.2019 20:51:12
    Asset      Size  Chunks             Chunk Names
server.js  2.54 MiB       0  [emitted]  server
Entrypoint server = server.js
  [13] external "fs" 42 bytes {0} [built]
  [17] external "path" 42 bytes {0} [built]
  [22] external "url" 42 bytes {0} [built]
  [24] external "http" 42 bytes {0} [built]
  [61] ../node_modules/fastify/lib/symbols.js 1.43 KiB {0} [built]
 [113] ../node_modules/fastify/lib/validation.js 4.93 KiB {0} [built]
 [180] ../node_modules/proxy-addr/index.js 5.84 KiB {0} [built]
 [185] ../node_modules/fastify/lib/hooks.js 2.71 KiB {0} [built]
 [247] ../node_modules/aws-serverless-express/index.js 643 bytes {0} [built]
 [248] ../src/server-config.js 1.21 KiB {0} [built]
 [256] ../node_modules/type-is/index.js 5.43 KiB {0} [built]
 [259] ../node_modules/find-my-way/index.js 18.1 KiB {0} [built]
 [479] ../node_modules/fastify/fastify.js 23.2 KiB {0} [built]
 [511] ../node_modules/aws-serverless-express/src/index.js 8.9 KiB {0} [built]
[1114] ./server.js + 54 modules 25.4 KiB {0} [built]
       | ./server.js 534 bytes [built]
       | ../src/instance.js 1.23 KiB [built]
       | ../src/config.js 1.12 KiB [built]
       | ../src/helpers/index.js 326 bytes [built]
       | ../src/env.js 599 bytes [built]
       | ../src/fastify-plugins/index.js 635 bytes [built]
       | ../src/errors/index.js 181 bytes [built]
       | ../src/routes/index.js 145 bytes [built]
       | ../src/middlewares/index.js 102 bytes [built]
       | ../src/helpers/has-key-obj.js 76 bytes [built]
       | ../src/helpers/key-generator.js 237 bytes [built]
       | ../src/helpers/ws.js 650 bytes [built]
       | ../src/helpers/db.js 78 bytes [built]
       | ../src/helpers/route-paths-normalizer.js 2.97 KiB [built]
       | ../src/helpers/console.js 545 bytes [built]
       |     + 40 hidden modules
    + 1103 hidden modules

WARNING in ../node_modules/uglify-es/tools/node.js 18:11-32
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/fast-json-stringify/index.js
 @ ../node_modules/fastify/lib/reply.js
 @ ../node_modules/fastify/fastify.js
 @ ../src/instance.js
 @ ./server.js

WARNING in ../node_modules/app-root-path/lib/app-root-path.js 14:10-56
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/app-root-path/index.js
 @ ../node_modules/fastify-oas/lib/openapi/constructor.js
 @ ../node_modules/fastify-oas/lib/openapi/index.js
 @ ../node_modules/fastify-oas/lib/index.js
 @ ../src/fastify-plugins/fastify-oas.js
 @ ../src/fastify-plugins/index.js
 @ ../src/instance.js
 @ ./server.js

WARNING in ../src/server-config.js
Module not found: Error: Can't resolve 'turbo-http/lib/server' in '/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/src'
 @ ../src/server-config.js
 @ ../src/instance.js
 @ ./server.js
Lambda server is listening on 9000
Request from ::ffff:127.0.0.1: GET /server
Response with status 500 in 167 ms.
Error during invocation:  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.dirname (path.js:1121:5)
    at e.exports (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:163:385690)
    at e.exports (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:163:384621)
    at Object.<anonymous> (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:163:384527)
    at Object.<anonymous> (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:163:384534)
    at n (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:1:158)
    at Object.<anonymous> (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:163:209951)
    at n (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:1:158)
    at Object.<anonymous> (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:163:209645)
    at n (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:1:158)
    at Object.<anonymous> (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:134:117610)
    at n (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:1:158)
    at Module.<anonymous> (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:273:267834)
    at n (/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:1:158)
    at /Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/functions-build/server.js:1:957
```

**Comment by dalisoft** [comment]
> WARNING in ../src/server-config.js
Module not found: Error: Can't resolve 'turbo-http/lib/server' in '/Users/dalisoft/Desktop/Dev Env from null/fastify-dev-env/src'

About this line, error is not caused by this, as i'm wrapped in try/catch + `require.resolve` on demand, not triggering when Lambda mode

**Comment by sw-yx** [comment]
yeah i'm not sure you can do this, import stuff from outside the functions folder: https://github.com/dalisoft/fastify-dev-env/blob/master/functions/server.js#L2

**Comment by dalisoft** [comment]
I think i got where problem, but thanks for help :)
You are right, not using DEV is easier

**Comment by dalisoft** [comment]
[Here](https://github.com/SkeLLLa/fastify-oas/issues/6) issue created, as issue refers to this repo
