### ISSUE TITLE
Node ModuleNotFound Error

### ISSUE THREAD

**Issue by david-j-davis** [netlify/netlify-lambda#169]
I've got a problem pulling in node modules to my functions folder, I'm only pulling in one node module which is 'mailgun-js' but I assume this would happen to any module. What am I missing here?
netlify-lambda v: 1.5.1

```
8:47:31 AM: Build ready to start
8:47:33 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
8:47:33 AM: build-image tag: v3.3.2
8:47:33 AM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
8:47:33 AM: Fetching cached dependencies
8:47:34 AM: Starting to download cache of 195.4MB
8:47:35 AM: Finished downloading cache in 1.594357165s
8:47:35 AM: Starting to extract cache
8:47:42 AM: Finished extracting cache in 7.125445916s
8:47:42 AM: Finished fetching cache in 8.788573349s
8:47:42 AM: Starting to prepare the repo for build
8:47:43 AM: Preparing Git Reference refs/heads/master
8:47:44 AM: Found netlify.toml. Overriding site configuration
8:47:44 AM: Different publish path detected, going to use the one specified in the toml file: './web/public' versus 'web/public' in the site
8:47:44 AM: Different build command detected, going to use the one specified in the toml file: 'yarn build' versus 'npm run build' in the site
8:47:44 AM: Different base path detected, going to use the one specified in the toml file: 'web/' versus '' in the site
8:47:44 AM: Starting build script
8:47:44 AM: Installing dependencies
8:47:45 AM: Started restoring cached node version
8:47:48 AM: Finished restoring cached node version
8:47:48 AM: v10.16.1 is already installed.
8:47:49 AM: Now using node v10.16.1 (npm v6.9.0)
8:47:50 AM: Attempting ruby version 2.6.2, read from environment
8:47:51 AM: Using ruby version 2.6.2
8:47:51 AM: Using PHP version 5.6
8:47:51 AM: Started restoring cached node modules
8:47:51 AM: Finished restoring cached node modules
8:47:51 AM: Started restoring cached yarn cache
8:47:51 AM: Finished restoring cached yarn cache
8:47:52 AM: Installing NPM modules using Yarn version 1.17.0
8:47:52 AM: yarn install v1.17.0
8:47:52 AM: warning ../package.json: No license field
8:47:53 AM: [1/4] Resolving packages...
8:47:53 AM: [2/4] Fetching packages...
8:48:18 AM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
8:48:18 AM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
8:48:18 AM: [3/4] Linking dependencies...
8:48:18 AM: warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
8:48:18 AM: warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
8:48:18 AM: warning "gatsby > gatsby-graphiql-explorer > graphiql-explorer@0.3.7" has incorrect peer dependency "graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
8:48:18 AM: warning "gatsby > gatsby-graphiql-explorer > graphiql > codemirror-graphql@0.7.1" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
8:48:18 AM: warning "gatsby > gatsby-graphiql-explorer > graphiql > codemirror-graphql > graphql-language-service-interface@1.3.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
8:48:18 AM: warning "gatsby > gatsby-graphiql-explorer > graphiql > codemirror-graphql > graphql-language-service-parser@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
8:48:18 AM: warning "gatsby > gatsby-graphiql-explorer > graphiql > codemirror-graphql > graphql-language-service-interface > graphql-config@2.0.1" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
8:48:18 AM: warning "gatsby > gatsby-graphiql-explorer > graphiql > codemirror-graphql > graphql-language-service-interface > graphql-language-service-types@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
8:48:18 AM: warning "gatsby > gatsby-graphiql-explorer > graphiql > codemirror-graphql > graphql-language-service-interface > graphql-language-service-utils@1.2.2" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
8:48:18 AM: warning "gatsby > gatsby-graphiql-explorer > graphiql > codemirror-graphql > graphql-language-service-interface > graphql-config > graphql-import@0.4.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
8:48:18 AM: warning "gatsby-plugin-sass > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
8:48:18 AM: warning " > react-chat-window@1.2.1" has incorrect peer dependency "react@15.x".
8:48:18 AM: warning "react-chat-window > react-highlight.js@1.0.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
8:48:18 AM: warning "react-chat-window > react-highlight.js@1.0.5" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
8:48:29 AM: [4/4] Building fresh packages...
8:48:33 AM: Done in 40.42s.
8:48:33 AM: NPM modules installed using Yarn
8:48:33 AM: warning ../package.json: No license field
8:48:33 AM: Started restoring cached go cache
8:48:33 AM: Finished restoring cached go cache
8:48:33 AM: unset GOOS;
8:48:33 AM: unset GOARCH;
8:48:33 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
8:48:33 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
8:48:33 AM: go version >&2;
8:48:33 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
8:48:33 AM: go version go1.12 linux/amd64
8:48:33 AM: Installing missing commands
8:48:33 AM: Verify run directory
8:48:33 AM: Executing user command: yarn build
8:48:34 AM: yarn run v1.17.0
8:48:34 AM: warning ../package.json: No license field
8:48:34 AM: $ yarn build:client && yarn build:microservices
8:48:34 AM: warning ../package.json: No license field
8:48:34 AM: $ gatsby build
8:48:37 AM: token: skGCzgWson6YAOcaiPLwFzA9uaV70YysPnp6kJEOuOsl7N3MMzZBYHUb4zheT0au75T8jiXJqkWoem3teTyHQKdRigqA7vgHc3QQXbLeKfvMgaoTEX1gjsB4IT9Msj0wZwZUF94F479l3YHjzfjXOlZeTxeeIiqYJ9lnkuY57JP4DwiBa7tW
8:48:37 AM: success open and validate gatsby-configs — 0.019 s
8:48:38 AM: success load plugins — 0.646 s
8:48:38 AM: success onPreInit — 0.004 s
8:48:38 AM: success delete html and css files from previous builds — 0.005 s
8:48:38 AM: success initialize cache — 0.008 s
8:48:38 AM: success copy gatsby files — 0.026 s
8:48:38 AM: info [sanity] Fetching remote GraphQL schema
8:48:38 AM: info [sanity] Transforming to Gatsby-compatible GraphQL SDL
8:48:38 AM: info [sanity] Stitching GraphQL schemas from SDL
8:48:38 AM: success onPreBootstrap — 0.442 s
8:48:38 AM: info [sanity] Fetching export stream for dataset
8:48:39 AM: info [sanity] Done exporting!
8:48:39 AM: success source and transform nodes — 0.687 s
8:48:39 AM: warning `createResolvers` passed resolvers for type `SanityRootQuery` that doesn't exist in the schema. Use `createTypes` to add the type before adding resolvers.
8:48:39 AM: success building schema — 0.341 s
8:48:39 AM: success createPages — 0.000 s
8:48:39 AM: success createPagesStatefully — 0.057 s
8:48:39 AM: success onPreExtractQueries — 0.004 s
8:48:39 AM: success update schema — 0.040 s
8:48:40 AM: success extract queries from components — 0.220 s
8:48:40 AM: success run static queries — 0.027 s — 3/3 114.76 queries/second
8:48:40 AM: success run page queries — 0.651 s — 6/6 9.22 queries/second
8:48:40 AM: success write out page data — 0.003 s
8:48:40 AM: success write out redirect data — 0.000 s
8:48:51 AM: success onPostBootstrap — 0.000 s
8:48:51 AM: info bootstrap finished - 17.518 s
8:49:32 AM: success Building production JavaScript and CSS bundles — 41.038 s
8:49:36 AM: success Building static HTML for pages — 3.694 s — 6/6 11.81 pages/second
8:49:36 AM: info Done building in 62.257 sec
8:49:37 AM: warning ../package.json: No license field
8:49:37 AM: $ netlify-lambda build ../microservices --config ../webpack.functions.js
8:49:37 AM: netlify-lambda: Building functions
8:49:38 AM: ModuleNotFoundError: Module not found: Error: Can't resolve 'mailgun-js' in '/opt/build/repo/microservices'
8:49:38 AM:     at factory.create (/opt/build/repo/web/node_modules/netlify-lambda/node_modules/webpack/lib/Compilation.js:888:10)
8:49:38 AM:     at factory (/opt/build/repo/web/node_modules/netlify-lambda/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
8:49:38 AM:     at resolver (/opt/build/repo/web/node_modules/netlify-lambda/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
8:49:38 AM:     at asyncLib.parallel (/opt/build/repo/web/node_modules/netlify-lambda/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
8:49:38 AM:     at /opt/build/repo/web/node_modules/neo-async/async.js:2830:7
8:49:38 AM:     at /opt/build/repo/web/node_modules/neo-async/async.js:6877:13
8:49:38 AM:     at normalResolver.resolve (/opt/build/repo/web/node_modules/netlify-lambda/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
8:49:38 AM:     at doResolve (/opt/build/repo/web/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
8:49:38 AM:     at hook.callAsync (/opt/build/repo/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
8:49:38 AM:     at _fn0 (eval at create (/opt/build/repo/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
8:49:38 AM:     at resolver.doResolve (/opt/build/repo/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
8:49:38 AM:     at hook.callAsync (/opt/build/repo/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
8:49:38 AM:     at _fn0 (eval at create (/opt/build/repo/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
8:49:38 AM:     at hook.callAsync (/opt/build/repo/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
8:49:38 AM:     at _fn0 (eval at create (/opt/build/repo/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
8:49:38 AM:     at resolver.doResolve (/opt/build/repo/web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
8:49:38 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
8:49:38 AM:     at hook.callAsync (/opt/build/repo/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
8:49:38 AM:     at _fn3 (eval at create (/opt/build/repo/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
8:49:38 AM:     at resolver.doResolve (/opt/build/repo/web/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
8:49:38 AM:     at hook.callAsync (/opt/build/repo/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
8:49:38 AM:     at _fn0 (eval at create (/opt/build/repo/web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
8:49:38 AM:     at hook.callAsync (/opt/build/repo/web/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
8:49:38 AM: resolve 'mailgun-js' in '/opt/build/repo/microservices'
8:49:38 AM:   Parsed request is a module
8:49:38 AM:   using description file: /opt/build/repo/microservices/package.json (relative path: .)
8:49:38 AM:     resolve as module
8:49:38 AM:       /opt/build/repo/microservices/node_modules doesn't exist or is not a directory
8:49:38 AM:       /opt/build/repo/node_modules doesn't exist or is not a directory
8:49:38 AM:       /opt/build/node_modules doesn't exist or is not a directory
8:49:38 AM:       /opt/node_modules doesn't exist or is not a directory
8:49:38 AM:       /node_modules doesn't exist or is not a directory
8:49:38 AM: error Command failed with exit code 1.
8:49:38 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
8:49:38 AM: error Command failed with exit code 1.
8:49:38 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
8:49:38 AM: Skipping functions preparation step: no functions directory set
8:49:38 AM: Caching artifacts
8:49:38 AM: Started saving node modules
8:49:38 AM: Finished saving node modules
8:49:38 AM: Started saving yarn cache
8:49:38 AM: Finished saving yarn cache
8:49:38 AM: Started saving pip cache
8:49:38 AM: Finished saving pip cache
8:49:38 AM: Started saving emacs cask dependencies
8:49:38 AM: Finished saving emacs cask dependencies
8:49:38 AM: Started saving maven dependencies
8:49:38 AM: Finished saving maven dependencies
8:49:38 AM: Started saving boot dependencies
8:49:38 AM: Finished saving boot dependencies
8:49:38 AM: Started saving go dependencies
8:49:38 AM: Finished saving go dependencies
8:49:38 AM: Error running command: Build script returned non-zero exit code: 1
8:49:38 AM: Failing build: Failed to build site
8:49:38 AM: Finished processing build request in 2m5.264653614s
```

**Comment by sw-yx** [comment]
do you have mailgun.js in your package.json? pardon the super basic question.

this ` warning ../package.json: No license field` warning  makes me wary that you are using a nonstandard setup. is it some sort of monorepo? make sure you're running `yarn install` in the right place for mailgun to be installed

**Comment by david-j-davis** [comment]
Hi @sw-yx, yes this is a monorepo, and in my functions folder I've got node_modules with 'mailgun-js' as an available package.

**Comment by sw-yx** [comment]
yes but do you have the same node_modules inside your functions folder in production? might need to run another install inside the functions folder as well. i typically set that up as a `prebuild` step in package.json

**Comment by david-j-davis** [comment]
@sw-yx ok, you mean `preinstall`, I set that up, but it seems it's not run, or I can't trigger it from my build command. I suppose I could do something like `"build:lambda": "cd ../microservices && yarn preinstall && cd ../web && netlify-lambda build ../microservices"`. This just seems ugly. It seems using monorepos with netlify-lambda I'm in the dark.

**Comment by sw-yx** [comment]
indeed its not a first class citizen but theres workarounds. you can also use a node script: https://community.netlify.com/t/functions-and-node-modules/2323/6?u=davidwells

**Comment by bravcmo** [comment]
I'm having a similar issue with mailgun-js where my functions work fine locally, but not in production -it seems clear that a root-level package.json should suffice for any required function modules, mailgun-js included.  Was there another workaround here that could be helpful to know about?  Thanks

**Comment by heymartinadams** [comment]
Critically, I think it’s important that the documentation gets updated to show something like this: in `package.json` file, build script:

`"build": "cd functions && yarn [or npm -i] && cd .. && [...rest of your build script]"`
