### ISSUE TITLE
devDependency "globby" not found

### ISSUE THREAD

**Issue by ArnaudSiebens** [netlify/netlify-lambda#173]
Version: 1.6.0

running `netlify dev` produces the following error, didn't receive this on the previous version (1.5.1):
```
Error: Command failed: npm run build
internal/modules/cjs/loader.js:628
    throw err;
    ^
Error: Cannot find module 'globby'
Require stack:
- D:/my-app/node_modules/netlify-lambda/lib/install.js
- D:/my-app/node_modules/netlify-lambda/bin/cmd.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:/my-app/node_modules/netlify-lambda/lib/install.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D://my-app//node_modules//netlify-lambda//lib//install.js',
    'D://my-app//node_modules//netlify-lambda//bin//cmd.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@1.0.0 build: `netlify-lambda build express`
npm ERR! Exit status 1
npm ERR!
```

I fixed this for the time being by installing globby manually.

**Comment by sw-yx** [comment]
thanks for the issue.

hmm, globby is a [devdependency](https://github.com/netlify/netlify-lambda/blob/e5c00a11762352968cecf02b357616df31afe1a0/package.json#L48). i guess it has to be promoted to a full dependency?

altho when i tested it in production today I did not have this problem.

**Comment by atymic** [comment]
I also got this error, solved by adding the package to my `package.json`. 
Would be good to get it fixed for new installs, though.

**Comment by sw-yx** [comment]
gotcha thanks for feedback
