### ISSUE TITLE
Cannot find @babel/core

### ISSUE THREAD

**Issue by nzakas** [netlify/netlify-lambda#20]
I’ve been using netlify-lambda and it throws an error whenever I use “serve”.

```
Nicholas@Patriot MINGW64 ~
$ node -v
v8.10.0

Nicholas@Patriot MINGW64 ~
$ npm -v
5.6.0
```

The full error is:

```
ERROR in ./subscribe.js
Module build failed: Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Nicholas\projects\personal\emails.humanwhocodes.com\node_modules\babel-loader\lib\transform.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Nicholas\projects\personal\emails.humanwhocodes.com\node_modules\babel-loader\lib\cache.js:24:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

This happens right at startup when testing locally and no functions will work. The function in this example simply prints out “OK”.

Is there something missing in the package for netlify-lambda?

**Comment by nzakas** [comment]
Note: I’m using latest. If I downgrade to 0.3.0, I don’t get this problem.

**Comment by biilmann** [comment]
Which version did you get when installing first time around? I'm wondering if the 1.0.0-babel-7-beta accidentally made it to the main line instead of a beta tag

**Comment by ahmedelgabri** [comment]
@biilmann yes `1.0.0-babel-7-beta` is the latest release on npm.

**Comment by nzakas** [comment]
Yup, latest is 1.0.0-babel-7-beta, that’s what gets installed by default with `npm install`

https://www.npmjs.com/package/netlify-lambda

**Comment by Cethy** [comment]
FWIW, I put `"@babel/core": "7.0.0-beta.42"` in my `package.json` to have it working.
