### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by bitttttten** [netlify/netlify-lambda#202]
Hi!

I am using nodejs 10, I have set `AWS_LAMBDA_JS_RUNTIME` to `nodejs10.x` in my environment variables in the Netlify UI. I am using async await in my code, although I run into this issue when testing my function:

```sh
{
"errorType": "ReferenceError",
"errorMessage": "regeneratorRuntime is not defined",
"trace": [
"ReferenceError: regeneratorRuntime is not defined",
"    at Object.<anonymous> (/var/task/index.js:1:1141)",
"    at i (/var/task/index.js:1:158)",
"    at Module.<anonymous> (/var/task/index.js:10:110372)",
"    at i (/var/task/index.js:1:158)",
"    at Object.<anonymous> (/var/task/index.js:9:114890)",
"    at Object.<anonymous> (/var/task/index.js:9:115993)",
"    at i (/var/task/index.js:1:158)",
"    at Object.<anonymous> (/var/task/index.js:9:114522)",
"    at Object.<anonymous> (/var/task/index.js:9:114837)",
"    at i (/var/task/index.js:1:158)"
]
}
```

The function looks a bit like this:

```js
// src/index.js
const generate = require('./lib/generate')

async function handler(event) {
    const qs = event.queryStringParameters || {}
    const qrcode = await generate({
        text: qs.text || 'hello world',
        margin: qs.margin || 1,
        quality: qs.quality || 'Q',
    })

    return {
        statusCode: 200,
        headers: {
            'Content-Type': 'image/png'
        },
        body: qrcode.toString('base64'),
        isBase64Encoded: true,
    }
}

exports.handler = handler
```

 I thought I could just include `require('@babel/polyfill')` at the top of my handler file, although that didn't seem to work either.

Am I missing something? I am just running `npm run build` here.

```js
// package.json
{
    "version": "1.0.0",
    "main": "dist/index.js",
    "scripts": {
        "build": "netlify-lambda build src"
    },
    "dependencies": {
        "data-uri-to-buffer": "^3.0.0",
        "jimp": "^0.8.5",
        "qrcode": "^1.4.2"
    },
    "devDependencies": {
        "netlify-lambda": "^1.6.3",
    }
}
```

```sh
# netlify.toml
[build]
  command = "npm run build"
  functions = "dist"
```

**Comment by bitttttten** [comment]
I imported

`require('@babel/polyfill/noConflict')`

at the top of my handler file. Although this is probably just a workaround, I'll close the issue. Happy to reopen and make a reproducible demo if necessary.
