### ISSUE TITLE
Error when running netlifycms plus netlify lambda

### ISSUE THREAD

**Issue by Hjkun77** [netlify/netlify-lambda#236]
Hi everyone! I'm having this error when I run my netlifycms but this just came up when I upgrade my node to version 14. Do I downgrade by node or not?

```
`Entrypoint hello = hello.js
[0] ./hello.js 1.75 KiB {0} [built] [failed] [1 error]

ERROR in ./hello.js
Module build failed (from /mnt/c/Users/Harvey Jay/Documents/Harvey/Projects/Gatsby Projects/gatsby-netlifycms-template/node_modules/netlify-lambda/node_modules/babel-loader/lib/index.js):

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /node_modules/netlify-lambda/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/node_modules/netlify-lambda/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)`
```

Here's a preview of my hello.js. Check it out in this link https://github.com/Hjkun77/gatsby-netlifycms-template/blob/develop/src/lambda/hello.js

Thank you

**Comment by erezrokah** [comment]
@Hjkun77, sorry for the late reply.
See https://github.com/babel/babel/issues/11216.
I was able to resolve the issue by deleting `yarn.lock` and running `yarn install` to get the updated versions.
Please comment if the solution doesn't work for you.
