### ISSUE TITLE
Exception has occurred: Error: Cannot find module 'encoding'

### ISSUE THREAD

**Issue by Voxlinou** [netlify/netlify-lambda#251]
Hi ^^' I've been creating my discord bot for awhile now and i got this error from no where.
I just opened vs code and tried to run my bot without editing anything !
```javascript
Exception has occurred: Error: Cannot find module 'encoding'
Require stack:
- c:\Users\admin\Desktop\Dossiers\Bot\node_modules\node-fetch\lib\index.js
- c:\Users\admin\Desktop\Dossiers\Bot\node_modules\discord.js\src\util\Util.js
- c:\Users\admin\Desktop\Dossiers\Bot\node_modules\discord.js\src\index.js
- c:\Users\admin\Desktop\Dossiers\Bot\index.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (c:\Users\admin\Desktop\Dossiers\Bot\node_modules\node-fetch\lib\index.js:162:12)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
```
Since index.js is mentionned here it is ;
```javascript
const Discord = require("discord.js");
const moment = require("moment")
const fs = require("fs");
const config = require('./config.json')
const client = new Discord.Client

client.login('don't look ;-;');

client.on('ready', () => {
	console.log('Logged in as ' + client.user.tag + ' !');

	client.user.setPresence({
		status: config.status,
		activity: {
			name: config.statustext,
			type: config.statustype,
		}
	})
  });
  client.on("message", async message => { 
    let messageArray = message.content.split(" ");
    let cmd = messageArray[0].toLowerCase();
    let args = messageArray.slice(1);
    let member = message.mentions.users.first() || message.author
    if(!message.content.startsWith('*')) return;
    let commandfile =
      client.commands.get(cmd.slice(config.prefix.length)) ||
      client.commands.get(client.aliases.get(cmd.slice(config.prefix.length)));
    if (commandfile) commandfile.run(client, message, args, member, moment, cmd)
  });
  client.commands = new Discord.Collection();
  client.aliases = new Discord.Collection();

  fs.readdir("./commands/", (err, files) => {
    let jsfile = files.filter(f => f.split(".").pop() === "js");
    if (jsfile.length <= 0) {
      return console.log("[LOGS] Couldn't Find Commands !");
    }
      jsfile.forEach((f, i) => {
    console.log('〚📫〛 Command ' + f.replace('.js','') + ' loaded');
    let pull = require(`./commands/${f}`);
    client.commands.set(pull.config.name, pull);
    pull.config.aliases.forEach(alias => {
      client.aliases.set(alias, pull.config.name);
    });
  });
});
```
If anyone know what's going on and have disord so we can talk very fast ♫ ฅ^✯-✯^ฅ ♪#3526

**Comment by Voxlinou** [comment]
Here is `loader.js`
[https://prnt.sc/tjkzmp](https://prnt.sc/tjkzmp)

**Comment by Lav-Hinsu** [comment]
just add 
`require('encoding')`
in the imports. works fine after that.

**Comment by erezrokah** [comment]
Closing per the suggested workaround. Please comment if still relevant.
https://github.com/netlify/zip-it-and-ship-it/issues/67#issuecomment-549837499 might also be related.

**Comment by luukdv** [comment]
@erezrokah Ran into the same issue, but I'm not using `node-fetch` anywhere (see https://github.com/netlify/netlify-lambda/issues/201). Wondering if `encoding` should be added as a dependency to `@netlify/plugin-functions-core`, like suggested in the linked issue?

This seems to keep popping up for different users. Thanks for having a look!

**Comment by erezrokah** [comment]
Hi @luukdv, thing is that this can happen with other dependencies too (see https://github.com/netlify/zip-it-and-ship-it/issues/67#issuecomment-549837499).

You can see more about proposed a workaround and solution in that issue comment.
