### ISSUE TITLE
netlify-lambda@2.0.0 build failure when function importing firebase-tools@7.16.2

### ISSUE THREAD

**Issue by daithimorton** [netlify/netlify-lambda#272]
**Describe the bug**
`netlify-lambda@2.0.0` build failure when function tries to import `firebase-tools@7.16.2`

```bash
npx netlify-lambda@2.0.0 build src/test        
netlify-lambda: Building functions
[
  ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  (Source code omitted for this binary file)
      at handleParseError (/Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/webpack/lib/NormalModule.js:469:19)
      at /Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/webpack/lib/NormalModule.js:503:5
      at /Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/webpack/lib/NormalModule.js:358:12
      at /Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/loader-runner/lib/LoaderRunner.js:373:3
      at iterateNormalLoaders (/Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
      at Array.<anonymous> (/Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
      at Storage.finished (/Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
      at /Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
      at /Users/dmorton/.npm/_npx/23549/lib/node_modules/netlify-lambda/node_modules/graceful-fs/graceful-fs.js:123:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
]
```

**To Reproduce**

```
npx create-react-app test && cd test
yarn add firebase-tools@7.16.2
mkdir -p src/test && echo "import firebaseTools from 'firebase-tools'" > src/test/test.js
echo '[build] 
  functions = "./functions"' > netlify.toml
npx netlify-lambda@2.0.0 build src/test
```

**Desktop (please complete the following information):**
Run the following command `npx envinfo --system --binaries --npmPackages netlify-lambda` and attach the output

```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.76 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  npmPackages:
    netlify-lambda: ^2.0.0 => 2.0.1 
```

**Additional context**

**Comment by daithimorton** [comment]
Ah, go here and read this https://github.com/netlify/netlify-lambda/blob/master/README.md#webpack-configuration

To fix this issue, after running the steps to reproduce this error, run the below commands. **IMPORTANT** use `netlify-lambda@2.0.1`

```bash
yarn add webpack-node-externals
echo "const nodeExternals = require('webpack-node-externals');

module.exports = {
    externals: [nodeExternals()],
};" > webpack.functions.js
npx netlify-lambda@2.0.1 build src/test --config webpack.functions.js
```
