### ISSUE TITLE
command line error message is confusing when toml file is missing publish property

### ISSUE THREAD

**Issue by rabbah** [netlify/netlify-lambda#32]
using version 0.4.0 via npm, neither `serve` or `build` commands recognize the given argument:

```
> netlify-lambda serve x
Starting server
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1246:7)
    at webpackConfig (/Users/rabbah/.node/lib/node_modules/netlify-lambda/lib/build.js:36:28)
    at Object.exports.watch (/Users/rabbah/.node/lib/node_modules/netlify-lambda/lib/build.js:103:26)
    at Command.<anonymous> (/Users/rabbah/.node/lib/node_modules/netlify-lambda/bin/cmd.js:28:11)
    at Command.listener (/Users/rabbah/.node/lib/node_modules/netlify-lambda/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/Users/rabbah/.node/lib/node_modules/netlify-lambda/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/rabbah/.node/lib/node_modules/netlify-lambda/node_modules/commander/index.js:474:21)
```

```
> netlify-lambda build x
Building functions
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1246:7)
    at webpackConfig (/Users/rabbah/.node/lib/node_modules/netlify-lambda/lib/build.js:36:28)
    at /Users/rabbah/.node/lib/node_modules/netlify-lambda/lib/build.js:93:13
    at new Promise (<anonymous>)
    at Object.exports.run (/Users/rabbah/.node/lib/node_modules/netlify-lambda/lib/build.js:92:10)
    at Command.<anonymous> (/Users/rabbah/.node/lib/node_modules/netlify-lambda/bin/cmd.js:48:8)
    at Command.listener (/Users/rabbah/.node/lib/node_modules/netlify-lambda/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)

```

**Comment by rabbah** [comment]
it appears the issue here is a missing "publish" property in the toml file; with the corresponding change below, the serve/build commands appear to now work as expected.

```
[build]
  publish = "_site"
  functions = "x"
```

re-titling the issue - perhaps a better error message is possible?

**Comment by sw-yx** [comment]
hi Rodric,

i'm not sure i follow. the toml file isn't part of this library? pls reopen if this is still an issue for you. thanks.

**Comment by dannysmith** [comment]
I'm getting the same error (though I have a toml file with `publish` in it).

Will do some more digging, but may be worth re-opening this?

For reference

```
Response with status 500 in 11 ms.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at /Users/danny/Desktop/booksapp/node_modules/netlify-lambda/lib/serve.js:54:23
    at Layer.handle [as handle_request] (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/layer.js:95:5)
    at /Users/danny/Desktop/booksapp/node_modules/express/lib/router/index.js:281:22
    at param (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/danny/Desktop/booksapp/node_modules/express/lib/router/index.js:365:14)
Hash: 7bce480933f387fe36cf
Version: webpack 4.26.0
```

**Comment by sw-yx** [comment]
sure, let me know what you find. keen to improve error msgs

**Comment by 8eecf0d2** [comment]
Afaict these two issues are unrelated.

@dannysmith what's the url you're requesting when this error occurs?

This error is most likely caused by a missing `functions` property in the `netlify.toml` or weird request `url`.

**Comment by dannysmith** [comment]
> Afaict these two issues are unrelated.

Yeah, I just worked that out! I can't remember exactly what my issue was, but I don't actually think it was to do with netlify-lambda in the end. 

Feel free to close - sorry for the bother!

**Comment by sw-yx** [comment]
we do need better error messages though.

**Comment by waffln** [comment]
For someone stumbling upon this issue: Naming your folder something like "func" will also throw a netlify-lambda error prompting you to rename the "functions" attribute in the netlify.toml. Rename the folder to something completely different, like "runner" and keep the attribute named "functions", then try again.

**Comment by sw-yx** [comment]
i’ll take suggestions for better error msgs all day. i believe i added something for this particular case but i dont get a ton of feedback

**Comment by itwasmattgregg** [comment]
I think the most confusing thing in the docs here is not understanding that your source folder and publish folder need to be different. It was confusing for me the first time getting set up. The error message says that an easy fix is to switch the key from functions to functions-build but I feel like it should say something more like change the value of `functions` to the directory you wand the functions built to.

**Comment by sw-yx** [comment]
pr always welcome :)

**Comment by itwasmattgregg** [comment]
@sw-yx I'll work on something soon. Also writing a blog post on this that should make sense of a lot of it.

**Comment by itwasmattgregg** [comment]
I've found it a lot easier to use netlify dev to build functions. it's pretty awesome

**Comment by sw-yx** [comment]
right? thank you.
