### ISSUE TITLE
Invalid webpack config

### ISSUE THREAD

**Issue by MartinMuzatko** [netlify/netlify-lambda#38]
The documentation doesn't say anything about a required webpack config, either the config in build.js is wrong, or there has to be a webpack config:

```sh
> # netlify-lambda build functions                                                                                                                                                                               
Building functions
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should not be empty.
      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
    at webpack (/usr/lib/node_modules/netlify-lambda/node_modules/webpack/lib/webpack.js:19:9)
    at /usr/lib/node_modules/netlify-lambda/lib/build.js:93:5
    at new Promise (<anonymous>)
    at Object.exports.run (/usr/lib/node_modules/netlify-lambda/lib/build.js:92:10)
    at Command.<anonymous> (/usr/lib/node_modules/netlify-lambda/bin/cmd.js:48:8)
    at Command.listener (/usr/lib/node_modules/netlify-lambda/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/lib/node_modules/netlify-lambda/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/lib/node_modules/netlify-lambda/node_modules/commander/index.js:474:21)

**Comment by fool** [comment]
Hey Martin, could you tell us what version of node you use here?

**Comment by MartinMuzatko** [comment]
node v 8.9.1

**Comment by okwme** [comment]
@MartinMuzatko make sure your `/functions` directory isn't empty

**Comment by MartinMuzatko** [comment]
I think we can close this. This was part of a misunderstanding with how to set up `netlify-lambda`. I hope so much that the documentation gets improved

**Comment by mriede** [comment]
I have this problem too, with a non-empty `./functions` folder, using Node v10.5.0
