### ISSUE TITLE
Cannot find module 'fs.realpath' react-scripts build

### ISSUE THREAD

**Issue by mbbender** [netlify/netlify-lambda#9]
I tried out your create react app inspired repo for the lambda functions and everything runs and builds fine locally, but when I try to run a deploy on netlify I get the errors below. I modified from `yarn` to `npm run` as you'll see below but got the same error for both. I also tried with the defautl node version which was 8 something but currently have it set to 9.4.0 and same errors on both.

```
10:23:11 AM: [4/4] Building fresh packages...
10:23:11 AM: Done in 22.33s.
10:23:11 AM: NPM modules installed using Yarn
10:23:12 AM: Installing missing commands
10:23:12 AM: Executing user command: npm run build && npm run build:lambda
10:23:12 AM: > react-lambda@0.1.0 build /opt/build/repo
10:23:12 AM: > react-scripts build
10:23:14 AM: module.js:557
10:23:14 AM:     throw err;
10:23:14 AM:     ^
10:23:14 AM: Error: Cannot find module 'fs.realpath'
10:23:14 AM:     at Function.Module._resolveFilename (module.js:555:15)
10:23:14 AM:     at Function.Module._load (module.js:482:25)
10:23:14 AM:     at Module.require (module.js:604:17)
10:23:14 AM:     at require (internal/module.js:11:18)
10:23:14 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/glob/glob.js:44:10)
10:23:14 AM:     at Module._compile (module.js:660:30)
10:23:14 AM:     at Object.Module._extensions..js (module.js:671:10)
10:23:14 AM:     at Module.load (module.js:573:32)
10:23:14 AM:     at tryModuleLoad (module.js:513:12)
10:23:14 AM:     at Function.Module._load (module.js:505:3)
10:23:14 AM:     at Module.require (module.js:604:17)
10:23:14 AM:     at require (internal/module.js:11:18)
10:23:14 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/rimraf/rimraf.js:7:12)
10:23:14 AM:     at Module._compile (module.js:660:30)
10:23:14 AM:     at Object.Module._extensions..js (module.js:671:10)
10:23:14 AM:     at Module.load (module.js:573:32)
10:23:14 AM: npm ERR! code ELIFECYCLE
10:23:14 AM: npm ERR! errno 1
10:23:14 AM: npm ERR! react-lambda@0.1.0 build: `react-scripts build`
10:23:14 AM: npm ERR! Exit status 1
10:23:14 AM: npm ERR!
10:23:14 AM: npm ERR! Failed at the react-lambda@0.1.0 build script.
10:23:14 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
10:23:14 AM: npm ERR! A complete log of this run can be found in:
10:23:14 AM: npm ERR!     /opt/buildhome/.npm/_logs/2018-02-08T15_23_14_046Z-debug.log
10:23:14 AM: Caching artifacts
10:23:14 AM: Cached NPM modules
10:23:14 AM: Saved Yarn cache
10:23:14 AM: Build complete: exit code: 1
10:23:14 AM: Error running command: Build script returned non-zero exit code: 1
10:23:14 AM: Failing build: Failed to build site
10:23:15 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:23:15 AM: Finished processing build request in 39.965670133s```

**Comment by sw-yx** [comment]
hi, sorry you ran into this. we've upgraded both versions now. can you retry?
